xmap <buffer> iE <Plug>(textobj-php-phparray-i)
omap <buffer> iE <Plug>(textobj-php-phparray-i)
xmap <buffer> ar <Plug>(textobj-php-phparray-a)
omap <buffer> ar <Plug>(textobj-php-phparray-a)
xmap <buffer> ie <Plug>(textobj-php-phptag-i)
omap <buffer> ie <Plug>(textobj-php-phptag-i)
xmap <buffer> ae <Plug>(textobj-php-phptag-a)
omap <buffer> ae <Plug>(textobj-php-phptag-a)
xmap <buffer> it <Plug>(multiselect-it)
omap <buffer> it <Plug>(multiselect-it)

